### PR TITLE
Add input pre-texts #13

### PR DESCRIPTION
**Pull request by ConnectNitish**
Generated a css class for setting min-width of every UI element to be of min length at least. Aligned all the input control's label with the same class.

### CODE REVIEW

**Comment by mmikaeleriksson** [comment]
Hi @ConnectNitish
I haven't had time to test this Pull Request but I noticed one thing.
Your PR includes code from your [last PR](https://github.com/mmikaeleriksson/workTime/pull/18)
It is a good idea to have a git branch per PR on your fork so that your code changes from older PRs aren't added in all your new PRs.

**Comment by ConnectNitish** [comment]
Ok sure will do git branch per PR. Please have a test on functionality as per your time.

**Comment by ConnectNitish** [comment]
Do I need to again take the Pull request for the PR and make changes in that by removing Old or this changes will be considerd.

**Comment by mmikaeleriksson** [comment]
@ConnectNitish It might be best to remove the changes and make a new branch with the changes and a new PR

**Comment by ConnectNitish** [comment]
Closing thie request. Will Raise with new PR.

**Comment by mmikaeleriksson** [comment]
This issue has already been solved in another PR

**Pull request closed without merging**
