### PR TITLE
Slightly brightened colors of links for dark mode

### PR DESCRIPTION
**Pull request by rydwhelchel**
This pull request resolves issue #53 

Description: Slightly brightened colors of links in the About section when the user is in dark mode.

### Checklist

I have:
* [x] Followed the library usage listed in [CONTRIBUTING.md/Library usage](../CONTRIBUTING.md#library-usage)
* [x] Followed indentation steps listed in [CONTRIBUTING.md/Indentation](../CONTRIBUTING.md#indentation)
* [x] Followed pull request steps listed in [CONTRIBUTING.md/Pull request](../CONTRIBUTING.md#pull-request)
* [x] Followed the code standard in the project

### CODE REVIEW

**Review by mmikaeleriksson — CHANGES_REQUESTED** [review]
The link color seems darker than before and the View on GithHub text seems to have changed as well.

image

**Comment by mmikaeleriksson** [comment]
> 
> 
> Wow that's embarrassing. I think I accidentally pushed the wrong changes.
> 
> While I'm here, I noticed that "visited" links in light mode don't change color.
> 
> Should I keep that functionality in dark mode? Before I push my corrected changes, this is what I've got now:


No worries 🙂

Sure, keep that functionality, so that it's equal regardless of color-mode.

**Comment by rydwhelchel** [comment]
For clarity, this is the new color scheme of the links.

image

**Review by mmikaeleriksson — APPROVED** [review]
Nice work. Merging

**Pull request merged**
