### PR TITLE
Add tab navigation to middle container

### PR DESCRIPTION
**Pull request by kimi43maro**
https://github.com/mmikaeleriksson/workTime/issues/15
- added tab navigation
- added dark-theme support for new Credits tab

### CODE REVIEW

**Comment by mmikaeleriksson** [comment]
@kimi43maro Nice work, had some comments in the review.

**Comment by kimi43maro** [comment]
I hope that this achieves what you meant in the comments. If not, let me know and I'll try to adjust 😅

**Comment by mmikaeleriksson** [comment]
@kimi43maro Looking good, nice work.
Some things I noticed:
* The 'lunch eaten' button will not work the first time pressed when the page is loaded.
* When loading the page in dark mode, the light/dark mode icon is still a sun.

**Comment by mmikaeleriksson** [comment]
@kimi43maro Looks great!
(Added comment right before this, was looking at wrong PR, sorry)

**Comment by kimi43maro** [comment]
Nice, glad I could help!

**Pull request merged**
