### PR TITLE
Fixing the bus icon using FontAwesome

### PR DESCRIPTION
**Pull request by Shubhayu-Das**
I have used FontAwesome: a free svg icon provider to fix this issue.

### CODE REVIEW

**Comment by Shubhayu-Das** [comment]
I have just noticed that there is a prior pull request with almost exactly the same changes as what I have made. Please consider the other person's pull request before accepting either of our solutions.

Thank you.

**Comment by mmikaeleriksson** [comment]
@Shubhayu-Das looking good, do you think you can change the other icons as well to use FontAwesome? So that only one icon library is used.
Notice that the lunch button has two icons depending on toggled state.

**Comment by mmikaeleriksson** [comment]
Hi @Shubhayu-Das, your fork seems to have fallen behind the master. Rebase your changes.
Nice work on the icons. Some things I noticed:
* Lunch eaten button does not seem to work the first time it is pressed.
* Light/dark mode icon is set to 'sun' when the page is loaded in dark mode. Should be set to right mode.

**Comment by Shubhayu-Das** [comment]
There is an issue with that. There should be a default fallback value when the onLoad event is triggered. What is happening is that the last state of the background is being saved when you close the webpage. But the buttons do have a default configuration, so they not synchronising properly.

I was planning on implementing an onLoad function, which will define the default state of all the variable classnames.

**Comment by Shubhayu-Das** [comment]
I am closing this thread and making a new Pull request. There are too many unnecessary commits here.

**Pull request closed without merging**
